version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"   # MQTT port
      - "9001:9001"   # WebSocket port (optional)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
